name: pcb_images

on:
  push:
    branches:
      - main
jobs:
  export_schematic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - uses: actions-for-kicad/generate-kicad-files@v1
        with:
          file: "./board/spark.kicad_sch"
          type: "schematic_svg"
          black-and-white: true

      - name: Move schematic SVG to correct location
        run: mv ./spark.svg ./images/schematic.svg

      - uses: stefanzweifel/git-auto-commit-action@v5

  render_pcb_images:
    needs: export_schematic
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
        time: '60s'
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - name: Render PCB image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "./board/spark.kicad_pcb"
          output_path: "${{ github.workspace }}/images"
          animation: "gif"
      - uses: stefanzweifel/git-auto-commit-action@v5