name: pcb_images

on:
  push:
    branches:
      - main

jobs:
  schematic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - uses: actions-for-kicad/generate-kicad-files@v1
        with:
          file: "./board/spark.kicad_sch"
          type: "schematic_svg"
          black-and-white: true

      - name: Move schematic SVG to correct location
        run: mv ./spark.svg ./images/schematic.svg

      - name: Commit schematic SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./images/schematic.svg
          git commit -m "Update schematic SVG"
          git push

  render_pcb_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - name: Render PCB image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "./board/spark.kicad_pcb"
          output_path: "${{ github.workspace }}/images"
          animation: "gif"

      - name: Commit PCB image
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./images/rotating.gif
          git add ./images/top.png
          git add ./images/bottom.png
          git commit -m "Update PCB images"
          git push