name: pcb_images

on:
  push:
    branches:
      - main

jobs:
  schematic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - uses: actions-for-kicad/generate-kicad-files@v1
        with:
          file: "./board/spark.kicad_sch"
          type: "schematic_svg"
          black-and-white: true

      # Move spark.svg to ./images/schematic.svg
      - name: Move schematic SVG to correct location
        run: mv ./spark.svg ./images/schematic.svg

      - name: Upload schematic SVG
        uses: actions/upload-artifact@v4
        with:
          name: "schematic.svg"
          path: "./images/schematic.svg"

  render_pcb_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"

      - name: Render PCB image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "./board/spark.kicad_pcb"
          output_path: "${{ github.workspace }}/images"
          animation: "gif"

      - name: Upload PCB image
        uses: actions/upload-artifact@v4
        with:
          name: "pcb_image.gif"
          path: "${{ github.workspace }}/images/*.gif"
